spring:
  config:
    activate:
      on-profile: "prod"

cards:
  message: "Hey Welcome to cards Microservice in production Environment"
  contact_details:
    name: "Asif"
    email: "{cipher}993b5477de0a4c676d5ceda27e91a034d63b9492c09f237423609b329917413e"
  on_call_support:
    - 9823232323
    - 9923523422



