spring:
  config:
    activate:
      on-profile: "default"
cards:
  message: "This is Cards Microservice in Local Environment"
  contact_details:
    name: "Asif in Local"
    email: "0a5d34c534910b2665bf6df4e71f073e3cd1abe88e54e196f405e34933"
  on_call_support:
    - 9823232323
    - 9923523422
