spring:
  config:
    activate:
      on-profile: "prod"

loans:
  message: "This is Loans MicroServices - PRODUCTION profile"
  contactDetails:
    name: "Asif"
    email: "azifussef139@gmail.com"
  onCallSupport:
    - 9992322222
    - 9002233333
