spring:
  config:
    activate:
      on-profile: "qa"

loans:
  message: "Hi Welcome to Loans MicroServices -QA profile"
  contactDetails:
    name: "Asif"
    email: "azifussef139@gmail.com"
  onCallSupport:
    - 9992322222

    - 9002233333

